version: '3'
services:
  my_db:
    image: mysql:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: mydb
      MYSQL_USER: omar
      MYSQL_PASSWORD: password

  my_node_image:
    build: .
    depends_on:
      - my_db
    ports:
      - 3000:8080
    restart: always

volumes:
  db_data:
